### ISSUE TITLE
Link for revision is missing a /

### ISSUE THREAD

**Issue by jdm** [dhananjay92/arewefastyet#9]
If I click on a node on http://ec2-52-88-122-83.us-west-2.compute.amazonaws.com/servo/ and click the `rev` link it takes me to https://github.com/servo/servo/commitsf30f40b12d2910f52e2274659e3762d9cd991649 .

**Comment by JayNakrani** [comment]
Ah, thanks for catching that.
~~Fixed in [9b2233](https://github.com/dhananjay92/arewefastyet/commit/9b2233).~~ 
Fixed in [2aa745](https://github.com/dhananjay92/arewefastyet/commit/2aa745b45dc89eb1f4f34b97a6e01961869bac99) :sweat_smile:
